### ISSUE TITLE
cannot get class after successfully imported

### ISSUE THREAD

**Issue by vanoak** [GodotVR/godot_openxr_vendors#233]
**System information**
Godot v4.3.stable - macOS 15.1.1 - GLES3 (Compatibility) - Apple M1 Pro - Apple M1 Pro (10 Threads)

**Issue description**
Followed the instructions in https://docs.godotengine.org/en/stable/tutorials/xr/setting_up_xr.html and https://docs.godotengine.org/en/stable/tutorials/xr/deploying_to_android.html.

After installing "Godot OpenXR Vendors plugin for Godot 4.3" from the assetlib which returns successfully, the output window show errors regarding not being able to get several classes.

<img width="1121" alt="Screenshot 2024-12-10 at 08 41 32" src="https://github.com/user-attachments/assets/a3caeed0-738c-4dec-8405-951b71767b0b">

The plugin doesn't show up in the project settings. 

<img width="662" alt="Screenshot 2024-12-10 at 08 41 49" src="https://github.com/user-attachments/assets/5f9a6239-3722-4d5b-92b7-653857efbb35">

**Steps to reproduce**
Follow the steps provided in the links above on a new empty project.

**EDIT**: Corrected name of the asset, english language corrections.

**Comment by The-Cyber-Captain** [comment]
Regarding the plugin not showing up; as per the Deploying To Android instructions, "Note: This is no longer required from vendors plugin 2.0.3 onwards as it now uses GDExtension. The plugin will not be shown in this list."

So that's normal, expected, behaviour. [Godot XR Tools for Godot 4.3 is currently serving up v3.0.1 of the plugin]

**Comment by The-Cyber-Captain** [comment]
Chiming in here just as a fellow user, I have now been able to replicate this behaviour on a Windows-run editor too. (I don't normally get the vendor plugin from the Asset Library, and don't believe I've ever witnessed these before due to that difference)

@vanoak - Looks to me as if these warnings are one-offs from the built-in IDE, and can safely - though not ideally, of course - be ignored... if you wish to continue with your project in the interim, that is. (I also happen to know that at least one of the plugin's major stakeholders develops on a Mac, too, so if the issue was a show-stopper it would bound to have been flagged by now!) 

Probably related to #96 ? And possible regression.

**Comment by The-Cyber-Captain** [comment]
Glad I could help. Looking forward to see whatever projects you're able to develop for the platform using the engine. Don't hesitate to reach out if you have any further issues.
